### ISSUE TITLE
Add bindings to blas/lapack?

### ISSUE THREAD

**Issue by dgrnbrg** [stainless-steel/matrix#1]
I was wondering if you'd accept a PR that integrated this tool with your blas/lapack crates? I'd like to expose their functions in a type-safe way (at least, the ones I'm initially interested in), and I'd also like to add support for some mathematica operators & higher-level functions, but only when an appropriate blas/lapack operator exists. The idea would be to add type-safe matrix & linear algebra operations that the developer knows are backed by their choice of blas & lapack.

**Comment by IvanUkhov** [comment]
Thanks for the issue! I’m a bit unsure what you’d like to do since `matrix` is already using `blas` and `lapack` for certain operations such as multiplication and eigendecomposition. Would you like to bring over some other functionality? Can you give an example?

Perhaps what you’re interested in has already been implemented in other crates such as [`ndarray`](https://crates.io/crates/ndarray) or [`linxal`](https://crates.io/crates/linxal); they also use BLAS/LAPACK under the hood.

**Comment by dgrnbrg** [comment]
What I'm imagining is lower-level than ndarray, but higher level than the raw blas/lapack bindings. 

1. I'd like to have traits for functionality like eigenvalues, eigenvectors/eigenvalues, cholesky decomp, svd, etc, but use traits on the various matrix types in this package to give compile-time assurance that the input format requires no additional translation/copying/allocation. For example, consider the variety of eigenproblem-related implementations in [netlib](http://www.netlib.org/lapack/lug/node31.html). I'd like to have these exposed on the types in this crate in a typesafe way, consuming, modifying, or creating new memory as needed (since, for example, many eigendecompositions consume the input matrix).
2. I'd like to have traits to convert between matrix representations explicitly and efficiently. In my numerical statistics code, I often use 3rd party packages that expect CCS or RCS encoded matrices, while I usually have row-major or upper-triangular packed representations in my own linear algebra. Safe conversions would allow for type-safe APIs and easier interop.

So, the idea is that since the types in this crate cover all the representations, I'd like to wrap the blas & lapack crates (as well as creating new conversion functions between representations), so that users who need lower-level control of the representation, but still want compile-time checks that they're using the APIs correctly, have an interface to work with.

Now, for some examples (which I 100% have not yet thought through the subtleties of the implementation):

```rust
// first, I'd like to wrap blas/lapack functions in types, like this for tridiagonal reduction of a symmetric matrix
fn dsptrd(matrix: Packed, banded_out: &mut Banded) -> Result<()>;
// These functions could runtime-check all the bounds of the matrices to ensure we never corrupt memory, which is possible with the blas/lapack crate directly.

// also, I'd like to have traits like this:
trait Eigenvalues<T> {
    fn eigenvalues(self) -> Result<Vec<T>>;
    fn eigendecomp(self) -> Result<(impl Matrix<T>, Vec<T>)>;
}

trait Matrix<T> {
   //I think it'd make sense to add this, too:
   fn element(i: usize, j: size) -> Result<T>;
}
```

These would allow the use of blas & lapack with almost no overhead (by minimizing allocation), but keep it all typesafe. My desire for this is motivated by the issues I've encountered and debugged in my use of the blas & lapack crates, and with my own numeric code.

**Comment by IvanUkhov** [comment]
I absolutely don’t mind enriching the functionality of this crate. In fact, the whole idea behind this crate was to provide diverse matrix operations for various matrix types and to accelerate them via BLAS/LAPACK whenever possible. The development stopped where it did simply because I had implemented everything that I needed for my projects.

If you have time and energy to help, I’ll be happy to receive and review pull requests from you. I just want to make sure that the content of this crate remains coherent, and than all the programming and naming conventions are well maintained.

Please start from something simple and open a separate pull request for each conceptual change. The smaller, the better. Please have a look at how certain operations have already been implemented such as the singular value decomposition and eigendecomposition in the [decomposition](https://docs.rs/matrix/0.21.6/matrix/decomposition/index.html) module.

Thanks!
